In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import tensorflow as tf

In [19]:
ratings_matrix = np.random.randint(0, 5, size=(4, 9))
ratings_matrix

array([[0, 2, 1, 3, 2, 1, 1, 1, 1],
       [0, 0, 1, 2, 2, 1, 0, 4, 1],
       [2, 2, 4, 4, 4, 3, 1, 0, 4],
       [4, 3, 1, 2, 0, 4, 3, 2, 4]])

In [27]:
for index1 in range(ratings_matrix.shape[0]):
    for index2 in range(ratings_matrix.shape[1]):
        ratings_matrix[index1, index2] += 1

In [28]:
ratings_matrix

array([[3, 4, 3, 5, 4, 3, 3, 3, 3],
       [3, 2, 3, 4, 4, 3, 2, 6, 3],
       [5, 4, 6, 6, 6, 5, 3, 2, 6],
       [7, 5, 3, 4, 2, 6, 5, 4, 6]])

In [16]:
initial_ratings = tf.placeholder(tf.float64, shape=ratings_matrix.shape)

In [4]:
ratings_matrix.shape

(4, 9)

In [5]:
number_of_latent_features = 4
number_of_users = ratings_matrix.shape[0]
number_of_items = ratings_matrix.shape[1]

In [33]:
left_values = np.random.uniform(size=(number_of_users, number_of_latent_features))
top_values = np.random.uniform(size=(number_of_latent_features, number_of_items))

In [34]:
left = tf.Variable(left_values)
top = tf.Variable(top_values)

In [35]:
result_matrix = tf.matmul(left, top)

In [36]:
error = result_matrix - initial_ratings

In [40]:
learning_rate = 0.1

In [10]:
error_trace = []

In [37]:
ratings_matrix - ratings_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    epochs = 500
    for i in range(epochs):
        left_values, top_values, result = sess.run([left, top, result_matrix])
        result, current_error = sess.run([result_matrix, error], feed_dict={initial_ratings:ratings_matrix})
        for index1 in range(current_error.shape[0]):
            for index2 in range(current_error.shape[1]):
                if current_error[index1, index2] < 0.0:
                    top_values[index1, index2] += learning_rate
                elif current_error[index1, index2] > 0.0:
                    top_values[index1, index2] -= learning_rate
        sess.run(top.assign(top_values))
    final_result = sess.run([result_matrix])

In [48]:
final_result

[array([[ -6.33244279,  -7.41042465,  -7.92448674,  -7.47551699,
          -7.42382894,  -6.87746025,  -7.32312783,  -4.83457515,
          -7.0126139 ],
        [ 29.3948041 ,  27.3698693 ,  25.43133948,  26.64958855,
          24.99433658,  28.19709355,  27.53643196,  -2.55304321,
          28.29163927],
        [-11.44667504, -12.91759189, -13.3072175 , -12.58024812,
         -11.40496131, -11.97223598, -12.83224024,  17.0532381 ,
         -12.3210762 ],
        [  7.05444568,   5.15573377,   3.18504432,   4.16813187,
           2.17760077,   6.02560214,   5.17310339,   4.1081933 ,
           6.07444705]])]

In [85]:
left_values

array([[0.84944717, 0.74707447, 0.93262892, 0.068411  ],
       [0.53843405, 0.85026753, 0.30181285, 0.83954895],
       [0.08976507, 0.14680962, 0.537944  , 0.14070203],
       [0.81691871, 0.9715177 , 0.29257988, 0.49974493]])

In [86]:
top_values

array([[0.58649769, 0.32305708, 0.20936797, 0.58898568, 0.52357111,
        0.36192882, 0.16444432, 0.00752639, 0.23017978],
       [0.17377467, 0.12995526, 0.47024484, 0.27478592, 0.24189584,
        0.40137419, 0.68770918, 0.10698268, 0.36741939],
       [0.07851974, 0.05664893, 0.66153133, 0.21358877, 0.73711296,
        0.32758481, 0.69355848, 0.70031996, 0.82933178],
       [0.56492711, 0.57103265, 0.97405308, 0.13060516, 0.73997658,
        0.91698949, 0.10822409, 0.83004644, 0.85062881]])

In [87]:
result

array([[0.73989843, 0.46340352, 1.21275414, 0.91373166, 1.36353561,
        0.97554306, 1.30769315, 0.79624026, 1.30166637],
       [0.96152751, 0.7809489 , 1.52998865, 0.72488475, 1.33130142,
        1.40487711, 0.97346349, 1.00324654, 1.40078892],
       [0.19988441, 0.15889732, 0.58074844, 0.22648676, 0.58315273,
        0.39665872, 0.50404665, 0.50990383, 0.64042206],
       [0.95323886, 0.69211021, 1.30821664, 0.87587385, 1.24818509,
        1.23971412, 1.05946498, 0.72979504, 1.21273583]])

In [88]:
result.shape

(4, 9)

In [109]:
current_error

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])